plugins {
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.androidKmpLibrary) apply false
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.ktlint) apply false
}

// Static analysis. This repo had none, so nothing checked the code that renders the portfolio site.
//
// `source` points at `src` rather than an enumerated list of source sets, because every list in the
// family had already drifted from reality: Kursi named five of fifteen and left production code in
// nativeMain, gms, noGms and main unscanned; PaymentsLab omitted wasmJsMain. Adding a target adds a
// source set, and nothing fails when the list is not updated to match — coverage shrinks silently
// while the build stays green. `src` cannot rot that way.
// Formatting. This repo declared no ktlint plugin at all until now — it carried 203 baselined
// detekt findings with nothing formatting the code behind them, and detekt's own MaxLineLength was
// left `active: false` with a comment claiming ".editorconfig / ktlint is the single source of
// truth for line length" when neither a ktlint plugin nor an .editorconfig existed. The claim is
// true now. Every rule disabled in .editorconfig is half a pair with an `active: false` in
// config/detekt/detekt.yml; changing one side alone puts the two tools back into contradiction.
subprojects {
    apply(plugin = "dev.detekt")
    apply(plugin = "org.jlleitschuh.gradle.ktlint")
    extensions.configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        version.set(rootProject.libs.versions.ktlintEngine)
        // Compose Resources writes Res.kt and the per-target resource collectors into build/, and
        // cmp-shared wires those generated dirs into composeMain as real source dirs. .editorconfig
        // already sets `ktlint = disabled` under build/, but without this filter the ktlint tasks
        // still take a build dependency on the codegen — formatting would start forcing a
        // resource-generation run.
        filter {
            exclude("**/build/**")
            exclude("**/data/generated/**")
        }
    }
    extensions.configure<dev.detekt.gradle.extensions.DetektExtension> {
        config.setFrom(rootProject.files("config/detekt/detekt.yml"))
        buildUponDefaultConfig = true
        parallel = true
        // Grandfathers findings that predate the gate so this lands green; new code is still gated.
        baseline = file("detekt-baseline.xml")
        source.setFrom(layout.projectDirectory.dir("src"))
    }
    // Both task types, not just Detekt. DetektCreateBaselineTask does NOT extend Detekt, so with
    // the exclusion on Detekt alone `detektBaseline` scanned src/**/data/generated/ that `detekt`
    // never looks at and wrote 10 MayBeConstant entries for findings the gate can never emit —
    // including one in CvOpsData.kt, a file this repo regenerates. A baseline entry that no run
    // can ever match is a dead entry, and dead entries are how a baseline stops meaning anything.
    tasks.withType<dev.detekt.gradle.Detekt>().configureEach {
        exclude("**/build/**", "**/generated/**")
    }
    tasks.withType<dev.detekt.gradle.DetektCreateBaselineTask>().configureEach {
        exclude("**/build/**", "**/generated/**")
    }
}

// CVE fix: ws < 8.21.0 is a high-severity memory-exhaustion DoS. It arrives transitively through
// Ktor's wasm client, whose generated package.json pins its version *exactly* — so editing
// kotlin-js-store/wasm/yarn.lock by hand cannot hold: the lock key is the requested descriptor, and
// yarn re-resolves the old version the moment the two disagree. A Yarn resolution is the only lever.
//
// Wasm has its own Yarn root, separate from JS: `WasmYarnRootExtension`, regenerated by
// `kotlinWasmUpgradeYarnLock` (NOT `kotlinUpgradeYarnLock`, which only touches kotlin-js-store/ and
// reports BUILD SUCCESSFUL without touching the wasm lock at all).
//
// The generated build/wasm/package.json is what carries `resolutions` — if it is stale it keeps an
// empty map and the resolution looks broken when it is not. Verify the fix at the artefact, not the
// exit code: `resolutions` in build/wasm/package.json, `version "8.21.0"` in the lock, and the
// version in build/wasm/node_modules/ws/package.json.
plugins.withType<org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnPlugin> {
    the<org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnRootExtension>().resolution("ws", "8.21.0")
}
