plugins {
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.androidKmpLibrary) apply false
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
}

// CVE fix: ws < 8.21.0 is a high-severity memory-exhaustion DoS. It arrives transitively through
// Ktor's wasm client, whose generated package.json pins its version *exactly* — so editing
// kotlin-js-store/wasm/yarn.lock by hand cannot hold: the lock key is the requested descriptor, and
// yarn re-resolves the old version the moment the two disagree. A Yarn resolution is the only lever.
//
// Wasm has its own Yarn root, separate from JS: `WasmYarnRootExtension`, regenerated by
// `kotlinWasmUpgradeYarnLock` (NOT `kotlinUpgradeYarnLock`, which only touches kotlin-js-store/ and
// reports BUILD SUCCESSFUL without touching the wasm lock at all).
//
// The generated build/wasm/package.json is what carries `resolutions` — if it is stale it keeps an
// empty map and the resolution looks broken when it is not. Verify the fix at the artefact, not the
// exit code: `resolutions` in build/wasm/package.json, `version "8.21.0"` in the lock, and the
// version in build/wasm/node_modules/ws/package.json.
plugins.withType<org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnPlugin> {
    the<org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnRootExtension>().resolution("ws", "8.21.0")
}
